apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecuacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecuacion
  template:
    metadata:
      labels:
        app: ecuacion
    spec:
      containers:
        - name: ecuacion
          image: sayid187/ecuacion:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ecuacion
spec:
  selector:
    app: ecuacion
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP