apiVersion: apps/v1
kind: Deployment
metadata:
  name: almacenar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: almacenar
  template:
    metadata:
      labels:
        app: almacenar
    spec:
      containers:
        - name: almacenar
          image: sayid187/almacenar:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: almacenar
spec:
  selector:
    app: almacenar
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP